---
keys:
    # Local development age recipient.
    - &client age1q4lfv04ytr7d7s8g0l9pnpewpzhhw4fxlx7jn2txwr47tyjn8d3qnl0wa0

creation_rules:
    - path_regex: secrets/[^/]+\.(yaml|yml|toml|json|env|ini)$
      key_groups:
        - age:
            - *client
