tap "dicklesworthstone/tap"
tap "felixkratz/formulae", "https://github.com/FelixKratz/homebrew-formulae"
tap "vanillacake369/tap"
brew "cosign"
brew "goreleaser"
brew "just"
brew "k3d"
brew "podman"
brew "podman-compose"
brew "showkey"
brew "slsa-verifier"
brew "tailscale", restart_service: :changed
cask "blackhole-2ch"
cask "brave-browser"
cask "buzz"
cask "cap"
cask "karabiner-elements"
cask "middleclick"
cask "monitorcontrol"
cask "multipass"
cask "obs"
cask "obsidian"
cask "podman-desktop"
cask "raycast"
cask "scroll-reverser"
cask "shottr"
cask "ticktick"
