#cloud-config
# Ansible Managed Node Template
# Uses default ubuntu user
# Replace {NODE_NAME} and {SSH_PUBLIC_KEY} before launching

hostname: {NODE_NAME}

# Package installation
packages:
  - net-tools
  - vim
  - python3
  - python3-pip

# SSH configuration
ssh_pwauth: true

# Add SSH public key to default ubuntu user
ssh_authorized_keys:
  - {SSH_PUBLIC_KEY}

# Setup commands
runcmd:
  # Ensure SSH directory permissions for ubuntu user
  - chmod 700 /home/ubuntu/.ssh
  - chmod 600 /home/ubuntu/.ssh/authorized_keys
  - chown -R ubuntu:ubuntu /home/ubuntu/.ssh

  # Create a helper script to display node info
  - |
    cat > /home/ubuntu/show-node-info.sh << 'EOF'
    #!/bin/bash
    echo "=========================================="
    echo "Ansible Managed Node Info"
    echo "=========================================="
    echo "Hostname: $(hostname)"
    echo "IP Address: $(hostname -I | awk '{print $1}')"
    echo ""
    echo "User: ubuntu"
    echo ""
    echo "SSH authorized for controlnode: YES"
    echo "Python version: $(python3 --version)"
    echo "=========================================="
    EOF
  - chmod +x /home/ubuntu/show-node-info.sh
  - chown ubuntu:ubuntu /home/ubuntu/show-node-info.sh

  # Display connection ready message
  - echo "Node {NODE_NAME} is ready for Ansible management" > /etc/motd

# Welcome message
final_message: |
  ========================================
  Ansible Managed Node ({NODE_NAME}) is ready!
  ========================================

  Default user: ubuntu

  This node is configured to accept SSH connections
  from the Ansible control node.

  To verify:
    1. multipass shell {NODE_NAME}
    2. ./show-node-info.sh

  ========================================
