Vagrant.configure("2") do |config|
  # Start with Ubuntu 22.04
  config.vm.box = "generic/ubuntu2204"

  # Update packages
  config.vm.provision "shell", inline: "sudo apt-get update -y", run: "once"


end
