{
  lib,
  spec,
}: let
  cfg = spec.aerospace;

  quote = value: "'${value}'";

  renderValue = value:
    if builtins.isBool value
    then
      (
        if value
        then "true"
        else "false"
      )
    else if builtins.isInt value
    then toString value
    else if builtins.isString value
    then quote value
    else if builtins.isList value
    then "[${lib.concatMapStringsSep ", " renderValue value}]"
    else throw "AeroSpace exporter: unsupported value ${builtins.typeOf value}";

  parseBind = expression: let
    parts = lib.splitString "+" expression;
    key = lib.last parts;
    rawModifiers = lib.init parts;
    modifiers = lib.flatten (map (
        modifier:
          if modifier == "caps"
          then ["ctrl" "alt"]
          else if modifier == "option"
          then ["alt"]
          else [modifier]
      )
      rawModifiers);
  in {
    inherit key;
    modifiers = lib.unique modifiers;
  };

  renderKey = key:
    if key == "left_arrow"
    then "left"
    else if key == "right_arrow"
    then "right"
    else if key == "up_arrow"
    then "up"
    else if key == "down_arrow"
    then "down"
    else if key == "equal_sign"
    then "equal"
    else if key == "hyphen"
    then "minus"
    else if key == "spacebar"
    then "space"
    else if key == "grave_accent_and_tilde"
    then "backtick"
    else key;

  renderBind = expression: let
    parsed = parseBind expression;
    prefix = lib.concatStringsSep "-" parsed.modifiers;
    key = renderKey parsed.key;
  in
    if prefix == ""
    then key
    else "${prefix}-${key}";

  renderBinding = binding: "${renderBind binding.bind} = ${renderValue binding.exec}";

  renderWindowRule = rule: ''
    [[on-window-detected]]
    ${lib.optionalString (rule ? app_id) "if.app-id = ${quote rule.app_id}\n"}
    ${lib.optionalString (rule ? app_name_regex) "if.app-name-regex-substring = ${quote rule.app_name_regex}\n"}
    ${lib.optionalString (rule ? check_further_callbacks) "check-further-callbacks = ${renderValue rule.check_further_callbacks}\n"}
    run = ${renderValue rule.run}
  '';

  inherit (cfg) settings gaps;
in ''
  # Generated from binds.toml by Nix.
  # Do not edit this file directly.

  config-version = ${toString settings.config_version}
  start-at-login = ${renderValue settings.start_at_login}
  enable-normalization-flatten-containers = ${renderValue settings.enable_normalization_flatten_containers}
  enable-normalization-opposite-orientation-for-nested-containers = ${renderValue settings.enable_normalization_opposite_orientation_for_nested_containers}
  accordion-padding = ${toString settings.accordion_padding}
  default-root-container-layout = ${renderValue settings.default_root_container_layout}
  default-root-container-orientation = ${renderValue settings.default_root_container_orientation}
  on-focused-monitor-changed = ${renderValue settings.on_focused_monitor_changed}
  automatically-unhide-macos-hidden-apps = ${renderValue settings.automatically_unhide_macos_hidden_apps}
  persistent-workspaces = ${renderValue settings.persistent_workspaces}

  [key-mapping]
  preset = ${renderValue cfg.key_mapping.preset}

  [gaps]
  inner.horizontal = ${toString gaps.inner_horizontal}
  inner.vertical = ${toString gaps.inner_vertical}
  outer.left = ${toString gaps.outer_left}
  outer.bottom = ${toString gaps.outer_bottom}
  outer.top = ${toString gaps.outer_top}
  outer.right = ${toString gaps.outer_right}

  [workspace-to-monitor-force-assignment]
  ${lib.concatMapStringsSep "\n" (
      entry: "${entry.workspace} = ${toString entry.monitor}"
    )
    cfg.workspace_assignments}

  [mode.main.binding]
  ${lib.concatMapStringsSep "\n" renderBinding cfg.bindings}

  [mode.service.binding]
  ${lib.concatMapStringsSep "\n" renderBinding cfg.service_bindings}

  ${lib.concatMapStringsSep "\n" renderWindowRule cfg.window_rules}
''
